CREATE TABLE IF NOT EXISTS Location (
	LocationID SERIAL PRIMARY KEY,
	LocationName VARCHAR(255) NOT NULL,
	Lat VARCHAR(50) NOT NULL,
	Long VARCHAR(50) NOT NULL,
	CreatedAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    UpdatedAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS Outing (
	OutingID SERIAL PRIMARY KEY,
	LocationID INT NOT NULL,
	FOREIGN KEY (LocationId) REFERENCES Location (LocationID),
	OutingDate DATE NOT NULL,
	StartTime TIME,
	EndTime TIME,
	CreatedAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    UpdatedAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS Catch (
	CatchID SERIAL PRIMARY KEY,
	OutingID INT NOT NULL,
	FOREIGN KEY (OutingID) REFERENCES Outing (OutingID),
	Species VARCHAR(50),
	CatchLength NUMERIC(5,2),
	CatchWeight NUMERIC(5,2),
	CreatedAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    UpdatedAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP
)